### ISSUE TITLE
vxTikTok broken

### ISSUE THREAD

**Issue by yeeterlol** [dylanpdx/vxtiktok#142] opened 2024-05-17 03:41 UTC
![image](https://github.com/dylanpdx/vxtiktok/assets/81702700/485c28a5-8747-4324-9501-819a94774225)
videos are broken now due to the new API changes

**Comment by foodornt** [comment] 2024-05-17 09:16
I can confirm

**Comment by dylanpdx** [comment] 2024-05-17 12:51
Will take a look

**Comment by Delphox** [comment] 2024-05-21 18:02
yt-dlp updated yesterday with support for all formats again using the web API, so updating yt-dlp and reverting the previous temporary fix should hopefully fix it.

**Comment by kpopdev** [comment] 2024-05-23 07:01
https://www.vxtiktok.com/@twice_tiktok_official/video/7372070699491511560 this link not working on discord its broken

**Comment by kpopdev** [comment] 2024-05-23 07:04
@dylanpdx please check https://www.vxtiktok.com/@twice_tiktok_official/video/7372070699491511560

**Comment by dylanpdx** [comment] 2024-05-23 17:59
Looks like this will be a slightly trickier fix, but I'll see what I can do

**Comment by dylanpdx** [comment] 2024-05-23 21:14
Videos should be fixed. Slideshows still are not working (refer to #136)
Will close if there are no major issues

**Comment by slisaasquatch** [comment] 2024-05-27 16:39
The videos now embed, but after the fix, the embedded videos can no longer play on iOS. They play on desktop just fine.

**Comment by ruukulada** [comment] 2024-06-06 18:48
Wondering if we can switch to [https://www.tfxktok.com](https://www.tfxktok.com) which works on iOS?

**Closed** 2024-08-15 13:09 UTC

**Comment by Harest** [comment] 2024-08-30 11:23
Seems the issue is back. At least on Discord currently, the videos are missing from the embeds.
